services:
  languagetool:
    image: erikvl87/languagetool:latest
    platform: linux/amd64
    container_name: languagetool
    restart: unless-stopped
    ports:
      - "8082:8010"
    environment:
      download_ngrams_for_langs: en
      langtool_languageModel: /ngrams
      Java_Xms: 512m
      Java_Xmx: 2g
    volumes:
      - languagetool_ngrams:/ngrams

volumes:
  languagetool_ngrams:
